# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts "Deleting user/sneaker data..."
User.destroy_all
Sneaker.destroy_all
Favorite.destroy_all
Sneaker.destroy_all

puts "Creating users..."
u1=User.create(first_name: 'Tremelle', last_name: 'Ancrum', avatar: '', username: 't123', email: 'tancrum1996@gmail.com', admin: true, password: '123')
u2=User.create(first_name: 'John', last_name: 'Doe', avatar: '', username: 't1234', email: 'crum1996@gmail.com', admin: true, password: '1234')
u3=User.create(first_name: 'T', last_name: 'A', avatar: '', username: 't12345', email: 'ancrum1996@gmail.com', admin: true, password: '12345')



puts "Creating favorites..."
f1=Favorite.create(user_id: u1.id)
f2=Favorite.create(user_id: u2.id)
f3=Favorite.create(user_id: u3.id)


puts "Creating carts..."
c1=Cart.create(user_id: u1.id)
c2=Cart.create(user_id: u2.id)
c3=Cart.create(user_id: u3.id)


puts "Creating sneakers..."
s1=Sneaker.create(name: 'LeBron 19', image: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/465ab10b-d24f-4d78-98eb-f94db71fbdbd/lebron-19-basketball-shoes-VkqHgW.png', price: 99.97, brand: 'Nike', user_id: u1.id, favorite_id: f1.id, cart_id: c1.id, amount: 1, description: 'LeBron thrives when stakes are high and the pressure’s on. The LeBron 19 harnesses that energy with a locked-in fit and an updated cushioning system. The snug inner sleeve is pulled together by a sculpted overlay that the laces feed through to help prevent the foot from moving inside the shoe. Embedded pods in the tongue and around the collar help reduce weight, keep the ankle aligned, and give players the secure feel and confidence to go all out when the game is on the line.')
s2=Sneaker.create(name: 'Air Jordan 3 Retro', image: 'https://images.stockx.com/images/Air-Jordan-3-Retro-Fire-Red-2022.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&dpr=2&trim=color&updated_at=1658172320&q=75', price: 230, brand:'Jordan', user_id: u2.id, favorite_id: f2.id, cart_id: c2.id, amount: 1, description: 'Nike needed a new designer to make the Air Jordan III. So they went to world famous Tinker Hatfield. His name is known mainly for designing Air Jordan III-XV, and also making a return on the AJ XXs, but Tinker also designed some really nice Nike’s as well. Tinker and Michael worked hard, talked to each other on what were good ideas, and what could “work”. Michael wanted a lightweight shoe, with a lot of durability. So with the Air Jordan 3 they both decided to make them a Mid top, the first mid top to be seen in the Air Jordan line. On the AJ III model Tinker placed the famous jumpman logo on the back of the shoe, and adding in a “elephant print” on the toe box. Also the IIIs were the first AJ to have a visible air-sole unit. In short, the inspirations for the AJ III are AJ I and II, the free throw dunk, an elephant, and last, but not least Michael Jordan.')
s3=Sneaker.create(name: 'Jordan ADG 4',  image: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/18f63d14-3acc-44e0-b198-c4b7c91d1d6d/jordan-adg-4-mens-golf-shoes-zw1ZGK.png', price: 185, brand:'Nike', user_id: u3.id, favorite_id: f3.id, cart_id: c3.id, amount: 1, description: 'A request from MJ himself, the Jordan ADG 4 infuses an incredibly classic silhouette with retro Jordan flavor. Supple, full-grain leather shows off the iconic elephant print on the heel. The rubber sole has an integrated traction pattern that perfectly pairs the grip you need with the versatility and comfort you want.' )
s4=Sneaker.create(name: 'Nike Air Zoom Pegasus 39', image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/57dd56da-b069-4c63-bece-4810c1067215/air-zoom-pegasus-39-mens-road-running-shoes-d4dvtm.png', price: 130, brand: 'Nike', user_id: u1.id, favorite_id: f1.id, cart_id: c1.id, amount: 1, description: 'The Nike Air Zoom Pegasus 39 is a mid-range running shoe that focuses on comfort rather than performance. This new model is lighter while retaining the winning formula of previous versions: precise lockdown, long-distance comfort, and noteworthy durability.' )
s5=Sneaker.create(name: 'Nike React Infinity Run Flyknit 3', image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f99c00c5-9286-4c9d-b3aa-20e3c16149ac/react-infinity-run-flyknit-3-womens-road-running-shoes-XpNmlR.png', price: 160, brand: 'Nike', user_id: u2.id, favorite_id: f2.id, cart_id: c2.id, amount: 1, description: 'The Nike React Infinity Run Flyknit 3 is a neutral, max-cushioned trainer that feels like a stability trainer due to its stability features which includes arch support and a plastic heel clip. It’s best used for easy, recovery and long-distance runs because of its high level of cushioning and its gentle rocker.')
s6=Sneaker.create(name: 'NikeCourt Zoom Pro', image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4fbc8ead-69be-4a94-8e41-a3566c510d48/nikecourt-zoom-pro-mens-hard-court-tennis-shoes-c5mPwW.png', price: 100, brand: 'Nike', user_id: u3.id, favorite_id: f3.id, cart_id: c3.id, amount: 1, description: 'The NikeCourt Men`s Zoom Pro Tennis Shoes pair classic styling with a modern Zoom Air unit in the forefoot. A full length plate is placed over the the Zoom Air unit and it acts like a springboard to enhance energy return with every step. The Zoom Pro features a soft mesh upper construction for enhanced breathability.')
s7=Sneaker.create(name: 'Nike Air Max 97', image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cuvuokzz86meuxcssbma/air-max-97-mens-shoes-LJmK45.png', price: 175, brand: 'Nike', user_id: u1.id, favorite_id: f1.id, cart_id: c1.id, amount: 1, description: 'The Nike Air Max 97 is a Nike running shoe designed by Christian Tresser. It was inspired by Japans Bullet Trains and features a mix of leather, foam, and full-length visible Air.')
s8=Sneaker.create(name: 'Air Jordan 12 Retro ', image: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/9890f9df-78dc-4307-83f5-e7dd738d6460/air-jordan-12-retro-shoes-kcMcpK.png', price: 200, brand: 'Jordan', user_id: u1.id, favorite_id: f1.id, cart_id: c1.id, amount: 1, description: 'The Air Jordan 12 was the first Air Jordan sneaker with Zoom Air cushioning. A full-length cushion was encased in Phylon and placed above a carbon fiber mid foot shank. The sneaker mostly built with premium full-grain leather, a detail that ended up being somewhat of a disadvantage due to its lack of breathability. The Air Jordan 12 Retro is the return of Tinker Hatfields celebrated 1996 design—the first to bring Zoom Air cushioning to the signature line. Premium materials in the upper give it a seasonal refresh.')
s9=Sneaker.create(name: 'Luka 1', image: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/db2d9edf-01db-46d9-98f1-5dc6e34ee3dc/luka-1-mens-basketball-shoes-11xlSZ.png', price: 110, brand: 'Jordan', user_id: u1.id, favorite_id: f1.id, cart_id: c1.id, amount: 1, description: 'The Luka 1 is designed for the deceptive, off-speed play of Luka Dončić, featuring a new IsoPlate system with full-length Formula 23 performance foam in the midsole. The shoe follows a long line of innovative Jordan Brand performance systems, like the Flight Plate in the Air Jordan XXVIII and the Eclipse Plate debuted in the Air Jordan XXXIV.')
s10=Sneaker.create(name: 'Nike Air VaporMax Plus', image: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/82e28136-6a86-4e33-a65c-6ef12f188ee6/air-vapormax-plus-mens-shoes-nC0dzF.png', price: 210, brand: 'Nike', user_id: u1.id, favorite_id: f1.id, cart_id: c1.id, amount: 1, description: 'Nikes Air VaporMax Plus adds state-of-the-art VaporMax tooling to the classic design of the 1998 Air Max Plus, effectively fusing past and future. It comes equipped with a floating mid-foot cage, TPU arch support, and revolutionary VaporMax Air cushioning under foot.')
s11=Sneaker.create(name: 'Converse Chuck Taylor All Star High Top', image: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ci5qxcnirgtzjpxztmvu/converse-chuck-taylor-all-star-high-top-unisex-shoe-xX439O.png', price: 65, brand: 'Converse', user_id: u1.id, favorite_id: f1.id, cart_id: c1.id, amount: 1, description: 'The iconic Chuck Taylor All Star high top shoes from Converse have a white leather upper, with red piping around the outsole. They have a vulcanized construction for a comfortable, broken-in fit, while the cushioned footbed ensures you have plenty of impact support.')
s12=Sneaker.create(name: 'NMD_R1 V2', image: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/e58f40b560904752b207adfb000c7b6b_9366/NMD_R1_V2_Shoes_Black_GY2071_01_standard.jpg', price: 150, brand: 'Adidas', user_id: u1.id, favorite_id: f1.id, cart_id: c1.id, amount: 1, description: 'Time is not slowing down. If anything, it seems to be moving at hyper-speed. And since the adidas NMD_R1 shoes are built on a foundation of speed, it only makes sense that these would be the perfect thing to lace into while you hold the pace of the day. The overlays add a futuristic edge to the streamlined silhouette. Boost cushioning makes every step feel like a good one — which is great since you are not slowing down either.')
s13=Sneaker.create(name: 'Yeezy Boost 700', image: 'https://images.solecollector.com/complex/images/c_fill,dpr_2.0,f_auto,fl_lossy,q_auto,w_800/bxz1yjtqcsxohk8wvawc/yeezy-wave-runner-700', price: 300, brand: 'Adidas', user_id: u1.id, favorite_id: f1.id, cart_id: c1.id, amount: 1, description: 'The original adidas Yeezy Boost 700 was Yeezy’s departure from the popular minimalist design aesthetic of the Yeezy Boost 350. Instead of utilizing monotone one-piece Primeknit construction, the silhouette featured layers of multicolored leather, suede, and mesh.')
s14=Sneaker.create(name: 'Yeezy Boost 700 v2', image: 'https://images.solecollector.com/complex/images/c_fill,dpr_2.0,f_auto,fl_lossy,q_auto,w_800/liwcumhizmzcrseeo6rx/adidas-yeezy-boost-700-v2-static-ef2829-release-date', price: 300, brand: 'Adidas', user_id: u1.id, favorite_id: f1.id, cart_id: c1.id, amount: 1, description: 'The adidas Yeezy Boost 700 V2 Vanta features a muted, all-black mesh, leather, and suede construction in a styling influenced by 1990s running shoes. At the base, a Boost-cushioned sole adds comfort and support.')
s15=Sneaker.create(name: 'NB 9060', image: 'https://nb.scene7.com/is/image/NB/u9060brn_nb_02_i?$pdpflexf22x$&fmt=webp&wid=944&hei=944', price: 149.99, brand: 'New Balance', user_id: u1.id, favorite_id: f1.id, cart_id: c1.id, amount: 1, description: 'After making its first appearance as a co-branded version with Joe Freshgoods namesake label, the retro-inspired 9060 was ready to indulge in GR makeovers. The NB 9060 model features a chunky profile clad with premium materials such as athletic mesh, smooth leather, and supple suede. In terms of colour arrangement, this versions sees a mix of brown, grey, and black. Classic New Balance branding details like the N logo on the lateral and medial sides, and a large bulbous midsole unit beneath the feet complete the look.')
s16=Sneaker.create(name: 'Shaq Attaq', image: 'https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/eb186b0fbb884eb9ada9aeb700040c2a_9366/Shaq_Attaq_Basketball_Shoes_White_GX3881_01_standard.jpg', price: 180, brand: 'Reebok', user_id: u1.id, favorite_id: f1.id, cart_id: c1.id, amount: 1, description: 'The Shaq Attaq 1 was originally released in 1992 and was the first signature sneaker for Shaquille O Neal from Reebok. They featured a leather and suede upper with Pump technology on the tongue and Graphlite.')




puts "Done Seeding"